# Generated by Django 5.1.1 on 2024-09-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usergallery_userproduct_user_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(upload_to='profiles/%Y/%m/%d/7c655c32-0ed3-4dd0-8acf-2def8706c4d5/'),
        ),
    ]
