# Generated by Django 5.1.1 on 2024-09-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='user',
        ),
    ]
