# Generated by Django 5.1.1 on 2024-09-05 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_remove_gallery_user'),
        ('users', '0002_usergallery_userproduct_user_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='like_users',
            field=models.ManyToManyField(related_name='liking_galleries', through='users.UserGallery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallery',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries', to=settings.AUTH_USER_MODEL),
        ),
    ]
