# Generated by Django 5.1.1 on 2024-09-06 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_gallery_like_users_gallery_owner'),
        ('users', '0002_usergallery_userproduct_user_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='liking_galleries', through='users.UserGallery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagetype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
