# Generated by Django 5.1.1 on 2024-09-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d/e1eba1f5-3d9a-40b6-8902-70132f39c36f/'),
        ),
    ]
